[project]
name = "odoo-addons-akretion-odoo-vat-prorata"
version = "18.0.20260526.0"
dependencies = [
    "odoo-addon-account_vat_pro_rata==18.0.*",
    "odoo-addon-account_vat_prorata_sector==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
